enum RoomType { GENERAL_ROOM, PRIVATE_ROOM, ICU_ROOM, EMERGENCY_ROOM, OPERATING_ROOM }

enum BedStatus { OCCUPIED, AVAILABLE }

enum PatientGender { MALE, FEMALE }

enum PatientCondition { STABLE, EMERGENCY, CRITICAL, NEEDS_SURGERY, RECOVERED }
